### ISSUE TITLE
Warning: Error in : Input must be a vector, not NULL.

### ISSUE THREAD

**Issue by iamericfletcher** [ramnathv/shinymetrics#10]
I am getting the following error when trying to reproduce David's dashboard demonstration in the broadway Youtube screencast.

```
Listening on http://127.0.0.1:7626
Warning: Error in : Input must be a vector, not NULL.
  84: <Anonymous>
Error : Input must be a vector, not NULL.
```

I am using the following code:

```
---
title: "Broadway Shows"
name: metrics_broadway_revenue
owner: EricFletcher3@gmail.com
metrics:
  usd_gross:
    title: Total Gross (USD)
    description: Not adjusted for inflation
  avg_ticket_price:
    title: Average Ticket Price
    description: Not adjusted for inflation
  pct_capacity:
    title: Percent capacity
    description: Average acros weeks in the time period
dimensions:
  show:
    title: Show
    description: Show's title
---
```

```
```{r}
library(tidyverse)
library(scales)
library(tidymetrics)
library(shinymetrics)
library(shinybones)
library(dplyr)
library(plotly)
install.packages("remotes")
remotes::install_github("ramnathv/shinymetrics")
remotes::install_github("ramnathv/tidymetrics")
remotes::install_github('ramnathv/shinybones')


tuesdata <- tidytuesdayR::tt_load('2020-04-28')
tuesdata

options(scipen=999)
theme_set(theme_light())
```
```{r}

shows_summarized <- grosses %>% 
  filter(show %in% c("Hamilton", "The Lion King",
                     "Les Miserables", "Rent", "The Phantom of the Opera", 
                     "Wicked", "Harry Potter and the Cursed Child, Parts One and Two",
                     "The Book of Mormon")) %>% 
  mutate(show = str_remove(show, "\\, Parts.*")) %>% 
  rename(date = week_ending) %>% 
  cross_by_dimensions(show) %>% 
  cross_by_periods(c("month", "quarter", "year"),
                   windows = 28) %>% 
  summarize(usd_gross = sum(weekly_gross),
            avg_ticket_price = mean(avg_ticket_price),
            pct_capacity =  mean(pct_capacity)) %>% 
  ungroup()


```
```
show_metrics <- create_metrics(shows_summarized)

preview_metric(show_metrics$broadway_revenue_usd_gross)
```

The module window opens briefly then crashes with the error provided above. 

Any ideas?
