### ISSUE TITLE
panel_metric doesn't support a metric with no dimensions

### ISSUE THREAD

**Issue by dgrtwo** [ramnathv/shinymetrics#4]
Example:

```
---
name: metrics_example_example
owner: drob
metrics:
  nb_example:
    title: Example
    description: Example
---
```

```
library(dplyr)
library(tidymetrics)
library(shinymetrics)

example_values <- tibble(date = Sys.Date() - 50:1) %>%
  mutate(nb_example = rnorm(n()),
         period = "day")

example_metrics <- create_metrics(example_values)

preview_metric(example_metrics$example_example_nb_example)
```

Result is an "Error: subscript out of bounds"
