### ISSUE TITLE
The percentage toggle is broken

### ISSUE THREAD

**Issue by dgrtwo** [ramnathv/shinymetrics#6]
The toggle to show metrics as a percentage out of a total is broken (it continues to show just the absolute total). Example:

```
---
name: metrics_example_example
owner: drob
metrics:
  nb_example:
    title: Example
    description: Example
dimensions:
  dimension:
    title: Example
    description: Example
---
```

```{r}
library(dplyr)
library(tidyr)
library(tidymetrics)
library(shinymetrics)

example_values <- crossing(date = Sys.Date() - 100:1,
                           dimension = c("Type 1", "Type 2")) %>%
    mutate(period = "day",
           nb_example = rpois(n(), 20))

example_metrics <- create_metrics(example_values)

preview_metric(example_metrics$example_example_nb_example)
```

![image](https://user-images.githubusercontent.com/994718/80580925-55962300-89da-11ea-82ce-5fd037ddb8d1.png)
