### ISSUE TITLE
metric_panel doesn't show "year" dimension

### ISSUE THREAD

**Issue by dgrtwo** [ramnathv/shinymetrics#7]
```
---
name: metrics_example_example
owner: drob
metrics:
  nb_example:
    title: Example
    description: Example
dimensions:
  dimension:
    title: Example
    description: Example
---
```

```{r}
library(dplyr)
library(tidyr)
library(tidymetrics)
library(shinymetrics)

example_values <- crossing(date = Sys.Date() - 10000:1,
                           dimension = c("Type 1", "Type 2")) %>%
    cross_by_periods(c("day", "month", "year")) %>%
    cross_by_dimensions(dimension) %>%
    summarize(nb_example = rpois(1, 20))

example_metrics <- create_metrics(example_values)

preview_metric(example_metrics$example_example_nb_example)
```

The aggregated by selector shows day and month, but not year:

![image](https://user-images.githubusercontent.com/994718/80581229-dd7c2d00-89da-11ea-812b-a3e01b4023a5.png)
